### ISSUE TITLE
Cleanup imports

### ISSUE THREAD

**Issue by mfirry** [vkostyukov/finch-101#2]
You probably need to get rid of these imports:
https://github.com/vkostyukov/finch-101/blob/master/src/main/scala/i/f/workshop/finch/Todo.scala#L16
https://github.com/vkostyukov/finch-101/blob/master/src/main/scala/i/f/workshop/finch/Time.scala#L7
https://github.com/vkostyukov/finch-101/blob/master/src/main/scala/i/f/workshop/finch/Greetings.scala#L7

**Comment by vkostyukov** [comment]
Fixed! Thanks again @mfirry!
